export const mockNamespaces = [
    {
        namespaceIdHex: '80DE90A24D6C0CC4',
        name: 'helloworld',
        isRoot: true,
        ownerAddressRawPlain: 'TCABUWAK5WMJ26ZPERMGWBOWAJF4XPNCJOWPAAI',
        aliasType: 0,
        aliasTargetAddressRawPlain: undefined,
        aliasTargetMosaicIdHex: undefined,
        parentNamespaceIdHex: '',
        startHeight: 611920,
        endHeight: 621920,
        depth: 0,
        metadataList: [],
    },
    {
        namespaceIdHex: '80DE90A24D6C0CC4',
        name: 'city.access',
        isRoot: true,
        ownerAddressRawPlain: 'TCABUWAK5WMJ26ZPERMGWBOWAJF4XPNCJOWPAAI',
        aliasType: 1,
        aliasTargetAddressRawPlain: undefined,
        aliasTargetMosaicIdHex: '632B3D23282A51E8',
        parentNamespaceIdHex: '',
        startHeight: 611920,
        endHeight: 621920,
        depth: 0,
        metadataList: [],
    },
    {
        namespaceIdHex: '80DE90A24D6C0CC4',
        name: 'symbolcity',
        isRoot: false,
        ownerAddressRawPlain: 'TCABUWAK5WMJ26ZPERMGWBOWAJF4XPNCJOWPAAI',
        aliasType: 2,
        aliasTargetAddressRawPlain: 'TCABUWAK5WMJ26ZPERMGWBOWAJF4XPNCJOWPAAI',
        aliasTargetMosaicIdHex: undefined,
        parentNamespaceIdHex: '',
        startHeight: 611920,
        endHeight: 621920,
        depth: 0,
        metadataList: [],
    },
];

export const mockNamespaceRowValue = {
    aliasIdentifier: 'N/A',
    aliasType: 'N/A',
    expiration: '29 d 23 h 58 m ',
    expired: false,
    hexId: '80DE90A24D6C0CC4',
    metadataList: [
        {
            metadataId: '62FC8624E173875059E72DE1',
            metadataType: 1,
            scopedMetadataKey: 'A14173CB00ED0041',
            sourceAddress: 'TCABUWAK5WMJ26ZPERMGWBOWAJF4XPNCJOWPAAI',
            targetAddress: 'TCABUWAK5WMJ26ZPERMGWBOWAJF4XPNCJOWPAAI',
            targetId: '7E77578D00C26DFC',
            value: 'metavalue',
        },
    ],
    name: 'helloworld',
};
